:aws:
  :access_key_id: ADD HERE
  :secret_access_key: ADD HERE
:s3:
  :region: ADD HERE # Note: for loading data into Redshift, your region needs to be US-standard
  :buckets:
    :in: ADD HERE
    :archive: ADD HERE
:download:
  :folder: ADD HERE # Infobright-only config option. Where to store the downloaded files. Note: only relevant for Infobright loads (not Redshift)
# Currently assumes we are loading only one target
:storage:
  :type: redshift # Or 'infobright'
  :endpoint: ADD HERE # Redshift only - get from Redshift console. Leave blank for Infobright
  :database: ADD HERE # Name of database 
  :port: 5039 # Typically '5039' for Redshift, '5029' for Infobright
  :table: events_007 # Latest version of table
  :username: ADD HERE 
  :password: ADD HERE 