:aws:
  :access_key_id: ADD HERE
  :secret_access_key: ADD HERE
:s3:
  :region: ADD HERE
  :buckets:
    :in: ADD HERE
    :processing: ADD HERE
    :archive: ADD HERE
# Currently assumes we are loading only one target
:storage:
  :type: infobright # No other storage types supported yet
  :database_name: ADD HERE
  :username: ADD HERE # Or leave blank to default to the user running the script
  :password: ADD HERE # Or leave blank if no password