:aws:
  :access_key_id: 'ADD HERE'
  :secret_access_key: 'ADD HERE'
:s3:
  :buckets:
    # Update assets if you want to host the serde and HiveQL yourself
    :assets: 's3://snowplow-emr-assets'
    :log: 'ADD HERE WITH PROTOCOL'
    :in: 'ADD HERE WITHOUT PROTOCOL'
    :processing: 'ADD HERE WITHOUT PROTOCOL'
    :out: 'ADD HERE WITHOUT PROTOCOL'
    :archive: 'ADD HERE WITHOUT PROTOCOL'
:emr:
  # Can bump the below as EMR upgrades Hadoop
  :hadoop_version: '1.0.3'
  :placement: 'ADD HERE'
  :ec2_key_name: 'ADD HERE'
  # Adjust your Hive cluster below
  :jobflow:
    :instance_count: 2
    :master_instance_type: 'm1.small'
    :slave_instance_type: 'm1.small'
# Can bump the below as SnowPlow releases new versions
:snowplow:
  :serde_version: '0.4.9'
  :hiveql_version: '0.4.10'