:aws:
	:access_key_id: ADD HERE
	:secret_access_key: ADD HERE
:s3:
	:location: ADD HERE
	:buckets:
		:assets: ADD HERE
		:in: ADD HERE
		:out: ADD HERE
		:archive: ADD HERE
:emr:
	:placement: ADD HERE
	:ec2_key_name: ADD HERE