:aws:
  :access_key_id: ADD HERE
  :secret_access_key: ADD HERE
:s3:
  :location: ADD HERE
  :buckets:
    # Update assets if you want to host the serde and HiveQL yourself
    # TODO: remove pbz- off the front
    :assets: s3://pbz-snowplow-emr-assets
    :in: ADD HERE
    :processing: ADD HERE
    :out: ADD HERE
    :archive: ADD HERE
:emr:
  :hadoop_version: "1.0.3"
  :placement: ADD HERE
  :ec2_key_name: ADD HERE
  :jobflow:
    :instance_count: 2
    :master_instance_type: 'm1.small'
    :slave_instance_type: 'm1.small'
#    action_on_failure: 'CONTINUE'
#    keep_job_flow_alive_when_no_steps: true
#  :hive_step:
#    action_on_failure: 'CONTINUE'
:snowplow:
  :serde_version: 0.4.9
  :hiveql_version: 0.4.10